[
  ../../modules/android
  ../../modules/flameshot
  ../../modules/gtk
  ../../modules/kitty
  ../../modules/nvim
  ../../modules/picom
  ../../modules/rofi
  ../../modules/tex
  ../../modules/zsh
]
